version: '3'

services:
  mongo:
    container_name: "jmalcloud_mongodb"
    image: "mongo:4.4"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./docker/mongodb/data/db:/data/db
      - ./docker/mongodb/custom:/etc/mongo
    restart: unless-stopped
    command: --bind_ip 127.0.0.1 --wiredTigerCacheSizeGB 0.5
  jmalcloud:
    container_name: "jmalcloud_server"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/jmalcloud:latest"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
      TZ: "Asia/Shanghai"
    ports:
      - "7072:8088"
    volumes:
      - ./docker/jmalcloud/files/:/jmalcloud/files/
    restart: unless-stopped
  nginx:
    container_name: "jmalcloud_nginx"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/nginx:latest"
    ports:
      - "7070:80"
      - "7071:8089"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/www/dist:/var/www/public
    environment:
      TZ: "Asia/Shanghai"
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: unless-stopped
  office:
    container_name: "jmalcloud_office"
    # x86:onlyoffice/documentserver:7.0.0.132, arm64:onlyoffice/documentserver:latest-arm64
    image: "${OFFICE_IMAGE}"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
  drawio-webapp:
    container_name: "jmalcloud_drawio"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/jgraph_drawio:16.6.1"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
