version: '3'

services:
  mongo:
    container_name: "${CONTAINER_NAME_PREFIX}_mongodb"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/mongodb:4.4${DOCKER_ARCH}"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ${RESOURCE_PATH}/mongodb/data/db:/data/db
      - ${RESOURCE_PATH}/mongodb/custom:/etc/mongo
      - ${RESOURCE_PATH}/mongodb/backup:/dump
    restart: unless-stopped
    ports:
      - "27018:27017"
    command: --wiredTigerCacheSizeGB 0.5
  jmalcloud:
    container_name: "${CONTAINER_NAME_PREFIX}_server"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/jmalcloud:latest${DOCKER_ARCH}"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
      TZ: "Asia/Shanghai"
    ports:
      - "${SERVER_PORT}:8088"
    volumes:
      - ${RESOURCE_PATH}/files/:/jmalcloud/files/
    restart: unless-stopped
  nginx:
    container_name: "${CONTAINER_NAME_PREFIX}_nginx"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/nginx:latest${DOCKER_ARCH}"
    ports:
      - "${APP_PORT}:80"
      - "${BLOG_PORT}:8089"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/www/dist:/var/www/public
    environment:
      TZ: "Asia/Shanghai"
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: unless-stopped
  office:
    container_name: "${CONTAINER_NAME_PREFIX}_office"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/onlyoffice_documentserver:${OFFICE_IMAGE_VERSION}"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
  drawio-webapp:
    container_name: "${CONTAINER_NAME_PREFIX}_drawio"
    image: "registry.cn-guangzhou.aliyuncs.com/jmalcloud/jgraph_drawio:16.6.1${DOCKER_ARCH}"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
