server:
  port: 8088
  servlet:
    encoding:
      force: true
spring:
  application:
    name: jmalcloud
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=3600s
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 2.2.34
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

